# Generated by Django 4.2.6 on 2023-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="first_name",
            field=models.TextField(default="mango"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_name",
            field=models.TextField(default="lassi"),
            preserve_default=False,
        ),
    ]
