# Generated by Django 4.2.6 on 2023-11-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_first_name_customuser_last_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_tutor",
            field=models.BooleanField(default=False),
        ),
    ]
