# Generated by Django 4.2.6 on 2023-11-23 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_customuser_is_tutor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="StudentProfile",
        ),
    ]
