# Generated by Django 4.2.6 on 2023-12-06 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_credentials",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
