# Generated by Django 4.2.6 on 2023-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_customuser_google_credentials"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="google_email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
