# Generated by Django 4.2.6 on 2023-12-21 13:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_customuser_google_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="balance",
            field=models.IntegerField(default=0),
        ),
    ]
