# Generated by Django 4.2.6 on 2023-12-21 13:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_customuser_balance"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="balance",
        ),
    ]
