# Generated by Django 4.2.6 on 2023-10-31 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='users.userprofile')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            bases=('users.userprofile',),
        ),
    ]
