# Generated by Django 4.2.6 on 2023-11-01 02:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="tutorprofile",
            name="tutor",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tutorprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tutors.subject"
            ),
        ),
        migrations.AddField(
            model_name="pricelist",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="tutors.tutorprofile"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pricelist",
            unique_together={("tutor", "subject")},
        ),
    ]
