# Generated by Django 4.2.6 on 2023-11-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0003_rename_tutor_tutorprofile_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pricelist",
            name="subject",
            field=models.IntegerField(
                choices=[(1, "Matematyka"), (2, "Fizyka"), (3, "Język angielski")],
                default=1,
            ),
            preserve_default=False,
        ),
    ]
