# Generated by Django 4.2.6 on 2023-11-09 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0004_pricelist_subject"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tutorprofile",
            name="price_list",
        ),
        migrations.RemoveField(
            model_name="tutorprofile",
            name="subjects",
        ),
        migrations.AddField(
            model_name="pricelist",
            name="tutor",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricelist_set",
                to="tutors.tutorprofile",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="pricelist",
            unique_together={("tutor", "subject")},
        ),
        migrations.DeleteModel(
            name="Subject",
        ),
    ]
