# Generated by Django 4.2.6 on 2023-11-23 20:21

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutors", "0005_remove_tutorprofile_price_list_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TutorProfile",
            new_name="Profile",
        ),
    ]
