# Generated by Django 4.2.6 on 2023-11-23 20:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0006_rename_tutorprofile_profile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="description_tutor",
            new_name="description",
        ),
    ]
