# Generated by Django 4.2.6 on 2023-11-27 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_profile"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("tutors", "0008_alter_profile_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.CharField(blank=True)),
                ("duration", models.IntegerField()),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField(editable=False)),
                (
                    "subject",
                    models.IntegerField(
                        choices=[
                            (1, "Matematyka"),
                            (2, "Fizyka"),
                            (3, "Język angielski"),
                        ]
                    ),
                ),
                (
                    "status",
                    models.IntegerField(
                        choices=[(1, "Planned"), (2, "Completed"), (3, "Cancelled")]
                    ),
                ),
                ("calendar_meet_link", models.CharField(max_length=500)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tutor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tutor_lessons",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="pricelist",
            name="tutor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pricelist_set",
                to="users.profile",
            ),
        ),
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
