# Generated by Django 4.2.6 on 2023-12-06 13:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tutors", "0009_lesson_alter_pricelist_tutor_delete_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lesson",
            name="end_time",
        ),
    ]
